### ISSUE TITLE
Is python 3 supported? Поддерживается ли python 3?

### ISSUE THREAD

**Issue by mrkaban** [CleanTalk/python-antispam#1]
The requirements specify Python 2.6 and above, so the question is, is python 3 supported? Although, judging by the fact that you only have one py file here, it means it is only for python 2.

Having such a module is good, great and ** very interesting **, but who is going to write sites in Python 2 now? Recent versions of Django no longer support Python 2.7, as it no longer receives security updates.

В требованиях указано Python 2.6 и выше, в связи с этим вопрос, поддерживается ли python 3? Хотя, если судить по тому, что у вас тут всего один файл py, значит он только для python 2.

Наличие такого модуля хорошо, замечательно и **очень интересно**, но кто сейчас будет писать сайты на Python 2? Последние версии Django уже по моему не поддерживают Python 2.7, так как он больше не получает обновлений безопасности.

**Comment by ardavydov** [comment]
Hello,

Thanks for your answer, we need some time (~1 week) to check the compatibility with Python 3.

**Comment by Glomberg** [comment]
Hello,
we have successfully tested the module on P2.7 and P3.9. So requirements are updated. https://github.com/CleanTalk/python-antispam/commit/16e6f484a1b42f84e9a09399e37d47ce3e8fedd9
