### ISSUE TITLE
DOES NOT WORK!!!

### ISSUE THREAD

**Issue by mrkaban** [CleanTalk/python-antispam#2]
DOES NOT WORK!!!

I put the cleantalk library in the application folder and imported it into views, the following code from views

`def contactView(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            ct = CleanTalk(auth_key='111')
            ct_result = ct.request(
                subject = form.cleaned_data['subject']
                name = form.cleaned_data['name']
                from_email = form.cleaned_data['from_email']
                message = form.cleaned_data['message']
            )
            if ct_result['allow']:
                msg = str(name) + '(' + str(from_email) + ')' + '\n отправил сообщение с темой "' + str(subject) + '":\n' + str(message)
                try:
                    send_mail(subject, msg, 'imail@mail.ru', ['mail@mail.ru'], fail_silently=False)
                except BadHeaderError:
                    return HttpResponse('Обнаружен недопустимый заголовок.')
                return redirect('success')
            else:
                raise forms.ValidationError("Blocked!!!!")
    return render(request, "email.html", {'form': form})
`

**Comment by mrkaban** [comment]
the error "Incomplete response received from application" appears and does not allow opening the site at all!

**Comment by mrkaban** [comment]
As soon as I remove your library and remove your code from views, everything works again!

**Comment by mrkaban** [comment]
[Python File.zip](https://github.com/CleanTalk/python-antispam/files/6487682/Python.File.zip)

**Comment by alexandergull** [comment]
Hello.
The application works fine.
I've sent you a few recommendations about your code. It needs to be improved. See the personal ticket 21929 in the CleanTalk ticket system.
WBR,

**Comment by mrkaban** [comment]
Thank you so much! Works!
