### ISSUE TITLE
pypi?

### ISSUE THREAD

**Issue by hasandiwan** [CleanTalk/python-antispam#3]
Is this available on PyPI? If not, is there any interest in making it available on the PYthon Package Index?

**Comment by alexandergull** [comment]
Hello @hasandiwan 

Thank you for your interest.

We plan to make it available on the PyPI within a few weeks. 

We will let you know.

**Comment by alexandergull** [comment]
Hello @hasandiwan 

We have published PyPi repo as requested.

https://pypi.org/project/cleantalk-python-antispam/

Thank you for waiting.
