### ISSUE TITLE
How to pass the url of the current page?

### ISSUE THREAD

**Issue by mrkaban** [CleanTalk/python-antispam#7]
Hello, please tell me how to transfer information about the current page? Suppose I have a URL_PAGE variable that stores the URL of the current page. How can I transfer information from it to you?

**Comment by alexandergull** [comment]
Hello. 

1) Checkout the dev version https://github.com/CleanTalk/python-antispam/blob/dev/cleantalk.py

2) Add a JSON object to the list of additional params (post_info) when you call the check. You requested for `post_url` - so specify it. Look at test examples.

```
...
    def test_blacklisted(self):
        response = self.ct.request(
            message='abc',  # Comment visitor to the site
            sender_ip='196.19.250.114',  # IP address of the visitor
            sender_email='s@cleantalk.org',  # Email IP of the visitor
            sender_nickname='spam_bot',  # Nickname of the visitor
            submit_time=12,  # The time taken to fill the comment form in seconds
            js_on=1,  # The presence of JavaScript for the site visitor, 0|1
            post_info=json.dumps({'post_url': 'https://text.com/1/2/3/4.html'}) # here is the place for page url
        )
        print(response)
...
```

Then you will see this URL in the CleanTalk dashboard logs.

**Comment by mrkaban** [comment]
Did you change something and not notify?

the code:
`ct_result = ct.request(
                message=content,  # Visitor comment
                sender_ip=clientIP,  # Visitor IP address
                sender_email=email,  # Visitor email
                sender_nickname=author,  # Visitor nickname
                js_on=1,  # Is visitor has JavaScript
                submit_time=12,  # Seconds from start form filling till the form POST
                post_info = json.dumps({'post_url': post_url})  # here is the place for page url
            )`
gives an error message:
`JSONDecodeError at /tkinterdesigner-graficheskij-interfejs-na-python/
Expecting value: line 1 column 1 (char 0)`
the problem is in **post_info = json.dumps({'post_url': post_url})**

This line gives an error on two sites, I did not change anything in the site settings.
