### ISSUE TITLE
Will this work with Django?

### ISSUE THREAD

**Issue by adambirds** [CleanTalk/python-antispam#8]
Will this work with Django?

How would we calculate the time taken to fill in the comment form or know if JS is on?

Thanks

**Comment by alexandergull** [comment]
Hello. 

This will work with Jango. The module is a standalone solution and independent of frameworks. 

Set a cookie via JS script on the page with the form. If the cookie is set and you can get it via python script it means the JS script was performed.

As for the submittime, I can't tell you how to do this right now. Probably you can use a cookie for page-generated timestamp and form submitting timestamp. Then calculate the diff.
