### ISSUE TITLE
Did you change something and not notify?

### ISSUE THREAD

**Issue by mrkaban** [CleanTalk/python-antispam#9]
Did you change something and not notify?

the code:
`ct_result = ct.request(
                message=content,  # Visitor comment
                sender_ip=clientIP,  # Visitor IP address
                sender_email=email,  # Visitor email
                sender_nickname=author,  # Visitor nickname
                js_on=1,  # Is visitor has JavaScript
                submit_time=12,  # Seconds from start form filling till the form POST
                post_info = json.dumps({'post_url': post_url})  # here is the place for page url
            )`
gives an error message:
`JSONDecodeError at /tkinterdesigner-graficheskij-interfejs-na-python/
Expecting value: line 1 column 1 (char 0)`
the problem is in **post_info = json.dumps({'post_url': post_url})**

This line gives an error on two sites, I did not change anything in the site settings.

_Originally posted by @mrkaban in https://github.com/CleanTalk/python-antispam/issues/7#issuecomment-1189168289_

**Comment by alexandergull** [comment]
Hi there. 

We have change nothing on your side since your last request.

JSONDecodeError means you try to decode something except an object, and seems this is your local issue.

Check what do you get in **post_url** variable. Then look for docs https://docs.python.org/3/library/json.html how can you rid this out.

**Comment by mrkaban** [comment]
well, listen, I didn't change anything in the code, but it worked on two different sites.

It's definitely not related to the code. Hosting here after all cannot be to blame, right?

Someone does not finish something)))) Okay, the main thing works, although it encourages us to come up with an alternative spam check.
